# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.CharField(choices=[('boss', 'jefe'), ('admin', 'administrador'), ('operator', 'operador')], max_length=8, verbose_name='Nivel'),
        ),
    ]
