# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20171112_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='non_paying',
        ),
        migrations.RemoveField(
            model_name='visits',
            name='payers',
        ),
    ]
